##############################################
## SEEE - COURS D'EAU : état biologique
## Application de l'arrêté de janvier 2010
##############################################


##############################
## Mise en forme des données
##############################
# DATABIO$STATION<-as.character(DATABIO$STATION)
# DATABIO$PARAMETRE<-as.character(DATABIO$PARAMETRE)
# DATABIO$PARAMETRELIB<-as.character(DATABIO$PARAMETRELIB)
# DATABIO$PARAGROUP<-as.character(DATABIO$PARAGROUP)
# DATABIO$RESULTAT<-as.numeric(DATABIO$RESULTAT)
# DATABIO$DATEPRELEV<-as.character(DATABIO$DATEPRELEV)
# DATABIO$HEUREPRELEV<-as.character(DATABIO$HEUREPRELEV)

gc() ## compacte R

########################################################
## Calcul de la moyenne de chaque indicateur de qualité
########################################################
BIO_MOY<-aggregate(RESULTAT ~ STATION + PARAGROUP, data = DATABIO , mean)
BIO_MOY$RESULTAT<-round(BIO_MOY$RESULTAT,2)
BIO_MOY<-BIO_MOY[order(BIO_MOY$STATION, BIO_MOY$PARAGROUP),]

BIO_MOY$CLASSEBIO<-as.numeric("")
BIO_MOY<-merge(BIO_MOY,STATION[,c("STATION", "TYPEFR")],by="STATION")
BIO_MOY_NAMES<-names(BIO_MOY)

#Calcul classe de qualité IBD
BIO_MOY<-merge(BIO_MOY,GRILLEIBD,by="TYPEFR", all.x=TRUE)
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="5856" & BIO_MOY$RESULTAT >=BIO_MOY$INFB]<-1
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="5856" & BIO_MOY$RESULTAT >=BIO_MOY$INFV & BIO_MOY$RESULTAT <BIO_MOY$INFB]<-2
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="5856" & BIO_MOY$RESULTAT >=BIO_MOY$INFJ & BIO_MOY$RESULTAT <BIO_MOY$INFV]<-3
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="5856" & BIO_MOY$RESULTAT >=BIO_MOY$INFO & BIO_MOY$RESULTAT <BIO_MOY$INFJ]<-4
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="5856" & BIO_MOY$RESULTAT >=BIO_MOY$INFR & BIO_MOY$RESULTAT <BIO_MOY$INFO]<-5

#Calcul classe de qualité IBG & IBGA
BIO_MOY<-BIO_MOY[,c(BIO_MOY_NAMES)]
BIO_MOY<-merge(BIO_MOY,GRILLEIBG,by="TYPEFR", all.x=TRUE)
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="5910" & BIO_MOY$RESULTAT >=BIO_MOY$INFB]<-1
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="5910" & BIO_MOY$RESULTAT >=BIO_MOY$INFV & BIO_MOY$RESULTAT <BIO_MOY$INFB]<-2
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="5910" & BIO_MOY$RESULTAT >=BIO_MOY$INFJ & BIO_MOY$RESULTAT <BIO_MOY$INFV]<-3
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="5910" & BIO_MOY$RESULTAT >=BIO_MOY$INFO & BIO_MOY$RESULTAT <BIO_MOY$INFJ]<-4
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="5910" & BIO_MOY$RESULTAT >=BIO_MOY$INFR & BIO_MOY$RESULTAT <BIO_MOY$INFO]<-5

BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="6951" & BIO_MOY$RESULTAT >=BIO_MOY$INFB]<-1
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="6951" & BIO_MOY$RESULTAT >=BIO_MOY$INFV & BIO_MOY$RESULTAT <BIO_MOY$INFB]<-2
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="6951" & BIO_MOY$RESULTAT >=BIO_MOY$INFJ & BIO_MOY$RESULTAT <BIO_MOY$INFV]<-3
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="6951" & BIO_MOY$RESULTAT >=BIO_MOY$INFO & BIO_MOY$RESULTAT <BIO_MOY$INFJ]<-4
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="6951" & BIO_MOY$RESULTAT >=BIO_MOY$INFR & BIO_MOY$RESULTAT <BIO_MOY$INFO]<-5

#Calcul classe de qualité IPR
BIO_MOY<-BIO_MOY[,c(BIO_MOY_NAMES)]
BIO_MOY<-merge(BIO_MOY,GRILLEIPR,by="PARAGROUP", all.x=TRUE)
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="7036" & BIO_MOY$RESULTAT >=0 & BIO_MOY$RESULTAT <=BIO_MOY$INFB]<-1
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="7036" & BIO_MOY$RESULTAT >BIO_MOY$INFB & BIO_MOY$RESULTAT <=BIO_MOY$INFV]<-2
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="7036" & BIO_MOY$RESULTAT >BIO_MOY$INFV & BIO_MOY$RESULTAT <=BIO_MOY$INFJ]<-3
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="7036" & BIO_MOY$RESULTAT >BIO_MOY$INFJ & BIO_MOY$RESULTAT <=BIO_MOY$INFO]<-4
BIO_MOY$CLASSEBIO[BIO_MOY$PARAGROUP=="7036" & BIO_MOY$RESULTAT >BIO_MOY$INFO ]<-5  # borne INFR sert uniquement pour le calcul de l'indice (limite max de l'indice 0)
BIO_MOY<-BIO_MOY[,c(BIO_MOY_NAMES)]
flush.console()

###################################################
## Calcul de l'état bio et mise en forme du tableau
###################################################
RLT_BIO<-aggregate(CLASSEBIO ~ STATION, data = BIO_MOY , max)
RLT_BIO<-RLT_BIO[order(RLT_BIO$STATION),]
names(RLT_BIO)[2]<-"ETATBIO"

for (i in  1:nrow(TABLEBIO)  ) {
	TEMPBIO<-BIO_MOY[BIO_MOY$PARAGROUP==TABLEBIO$PARAGROUP[i],c("STATION", "CLASSEBIO")]
	names(TEMPBIO)[2]<-TABLEBIO$PARALIBGROUP[i]
	RLT_BIO<-merge(RLT_BIO,TEMPBIO,by="STATION", all.x=TRUE)
	rm(TEMPBIO)
}

########################################
# Calcul Nb indicateur bio présents & listing
######################################
NBBIO<-RLT_BIO
NBBIO$NBINDICBIO<-as.numeric(0)
NBBIO$NBINDICBIO[!is.na(NBBIO$IBD)]<-NBBIO$NBINDICBIO[!is.na(NBBIO$IBD)]+1
NBBIO$NBINDICBIO[!is.na(NBBIO$IPR)]<-NBBIO$NBINDICBIO[!is.na(NBBIO$IPR)]+1
NBBIO$NBINDICBIO[!is.na(NBBIO$IBMR)]<-NBBIO$NBINDICBIO[!is.na(NBBIO$IBMR)]+1	
if (BASSIN =="AESN"){ # AESN moyenne IBGA et IBG --> ligne spécifique sinon condition marche pas
	NBBIO$NBINDICBIO[!is.na(NBBIO$IBG)]<-NBBIO$NBINDICBIO[!is.na(NBBIO$IBG)]+1 
} else {
	NBBIO$NBINDICBIO[!is.na(NBBIO$IBG) | !is.na(NBBIO$IBGA)]<-NBBIO$NBINDICBIO[!is.na(NBBIO$IBG) | !is.na(NBBIO$IBGA)]+1 
}

NBBIO$LISTINDICBIO<-as.character("")
NBBIO$LISTINDICBIO[!is.na(NBBIO$IBD)]<-"IBD"
if (BASSIN =="AESN"){ # AESN moyenne IBGA et IBG --> ligne spécifique sinon condidation marche pas
	NBBIO$LISTINDICBIO[!is.na(NBBIO$IBG)]<-paste0(NBBIO$LISTINDICBIO[!is.na(NBBIO$IBG)],";IBG") 
} else {
	NBBIO$LISTINDICBIO[!is.na(NBBIO$IBG) | !is.na(NBBIO$IBGA)]<-paste0(NBBIO$LISTINDICBIO[!is.na(NBBIO$IBG) | !is.na(NBBIO$IBGA)],";IBG")  
}
NBBIO$LISTINDICBIO[!is.na(NBBIO$IPR)]<-paste0(NBBIO$LISTINDICBIO[!is.na(NBBIO$IPR)],";IPR")
NBBIO$LISTINDICBIO[!is.na(NBBIO$IBMR)]<-paste0(NBBIO$LISTINDICBIO[!is.na(NBBIO$IBMR)],";IBMR")

# retrait du ";" si c'est le 1er symbole, pour faire propre dans tableau
cond1<-substr(NBBIO$LISTINDICBIO,1,1)==";"
NBBIO$LISTINDICBIO[cond1]<-substr(NBBIO$LISTINDICBIO[cond1],2,nchar(NBBIO$LISTINDICBIO[cond1]))

NBBIO_NAMES<-c("NBINDICBIO","LISTINDICBIO") # création names pour mise en forme du fichier final exporté
RLT_BIO<-NBBIO

gc() ## compacte R
flush.console()
