##### 7 Juillet 2016



###################
## CONTA : FREQUENCE
###################



if (CONTA == "oui" & TYPECONTA %in% c(1:3) ) {

RLT_CONTAFREQ<-data.frame(STATION = sort(unique(RLT_CONTA$STATION)))

	# Ajout colonnes des paramètres 
	PARAMETRECONTA_ETUDIE<-PARAMETRECONTA[PARAMETRECONTA$PARAMETRE %in% CONTAAGG$PARAMETRE,]

	for (i in  1:nrow(PARAMETRECONTA_ETUDIE)  ) {
		TEMPP<-CONTAAGG[CONTAAGG$PARAMETRE==PARAMETRECONTA_ETUDIE$PARAMETRE[i],c("STATION", "FREQ")]
		names(TEMPP)[2]<-PARAMETRECONTA_ETUDIE$NOMCOURT[i]
		RLT_CONTAFREQ<-merge(RLT_CONTAFREQ,TEMPP,by="STATION", all.x=TRUE)
		rm(TEMPP)
	}


RLT_CONTAFREQQUANTI<-data.frame(STATION = sort(unique(RLT_CONTA$STATION)))

	# Ajout colonnes des paramètres 
	PARAMETRECONTA_ETUDIE<-PARAMETRECONTA[PARAMETRECONTA$PARAMETRE %in% CONTAAGG$PARAMETRE,]

	for (i in  1:nrow(PARAMETRECONTA_ETUDIE)  ) {
		TEMPP<-CONTAAGG[CONTAAGG$PARAMETRE==PARAMETRECONTA_ETUDIE$PARAMETRE[i],c("STATION", "FREQQUANTI")]
		names(TEMPP)[2]<-PARAMETRECONTA_ETUDIE$NOMCOURT[i]
		RLT_CONTAFREQQUANTI<-merge(RLT_CONTAFREQQUANTI,TEMPP,by="STATION", all.x=TRUE)
		rm(TEMPP)
	}
	
	
}

#if (CONTA == "oui" & TYPECONTA %in% c(4) ) {
#	RLT_CONTAFREQ<-CONTAFREQ
#}



