##Création de l'onglet INDICE
##### 7 Juillet 2016

# principe de calcul de l'indice
# (((résultat - valeur inf borne)*25) / (valeur sup borne - valeur inf borne)) + indice borne inf
#SAVE()
####################################
## CONTAMINATION : VALEUR MOYENNE & INDICE 
######################################
if (CONTA=="oui") {
	
	CONTAINDICE<-CONTAAGG
	CONTAINDICE$INDICECONTA<-as.numeric("")

	cond1<-CONTAINDICE$CLASSECONTA==1 & !is.na(CONTAINDICE$CLASSECONTA)
	cond2<-CONTAINDICE$CLASSECONTA==2 & !is.na(CONTAINDICE$CLASSECONTA)
	cond3<-CONTAINDICE$CLASSECONTA==3 & !is.na(CONTAINDICE$CLASSECONTA)
	cond4<-CONTAINDICE$CLASSECONTA==4 & !is.na(CONTAINDICE$CLASSECONTA)
	cond5<-CONTAINDICE$CLASSECONTA==5 & !is.na(CONTAINDICE$CLASSECONTA)
	cond6<-CONTAINDICE$CLASSECONTA==6 & !is.na(CONTAINDICE$CLASSECONTA)

	if (NBSEUIL == 3 ) {

		CONTAINDICE$VALSEUIL4<-CONTAINDICE$VALSEUIL3 + (CONTAINDICE$VALSEUIL3 - CONTAINDICE$VALSEUIL2)

		CONTAINDICE$INDICECONTA[cond1]<-round((((CONTAINDICE$VALSEUIL1[cond1]-CONTAINDICE$RESULTAT2[cond1])*25)/(CONTAINDICE$VALSEUIL1[cond1]-0))+75)  
		CONTAINDICE$INDICECONTA[cond2]<-round((((CONTAINDICE$VALSEUIL2[cond2]-CONTAINDICE$RESULTAT2[cond2])*25)/(CONTAINDICE$VALSEUIL2[cond2]-CONTAINDICE$VALSEUIL1[cond2]))+50)
		CONTAINDICE$INDICECONTA[cond3]<-round((((CONTAINDICE$VALSEUIL3[cond3]-CONTAINDICE$RESULTAT2[cond3])*25)/(CONTAINDICE$VALSEUIL3[cond3]-CONTAINDICE$VALSEUIL2[cond3]))+25)
		CONTAINDICE$INDICECONTA[cond4]<-round((((CONTAINDICE$VALSEUIL4[cond4]-CONTAINDICE$RESULTAT2[cond4])*25)/(CONTAINDICE$VALSEUIL4[cond4]-CONTAINDICE$VALSEUIL3[cond4]))+0)
		CONTAINDICE$INDICECONTA[CONTAINDICE$RESULTAT2>CONTAINDICE$VALSEUIL4 & CONTAINDICE$CLASSECONTA==4]<-0
		CONTAINDICE$INDICECONTA[CONTAINDICE$INDICECONTA < 0]<-0
		CONTAINDICE$INDICECONTA[CONTAINDICE$INDICECONTA > 100]<-100
		rm(cond1, cond2, cond3, cond4,cond5)
	}

	if (NBSEUIL == 4 ) {

		CONTAINDICE$VALSEUIL4<-CONTAINDICE$VALSEUIL3 + (CONTAINDICE$VALSEUIL3 - CONTAINDICE$VALSEUIL2)
		CONTAINDICE$INDICECONTA[cond1]<-100
		CONTAINDICE$INDICECONTA[cond2]<-round((((CONTAINDICE$VALSEUIL1[cond2]-CONTAINDICE$RESULTAT2[cond2])*25)/(CONTAINDICE$VALSEUIL1[cond2]-0))+75)  
		CONTAINDICE$INDICECONTA[cond3]<-round((((CONTAINDICE$VALSEUIL2[cond3]-CONTAINDICE$RESULTAT2[cond3])*25)/(CONTAINDICE$VALSEUIL2[cond3]-CONTAINDICE$VALSEUIL1[cond3]))+50)
		CONTAINDICE$INDICECONTA[cond4]<-round((((CONTAINDICE$VALSEUIL3[cond4]-CONTAINDICE$RESULTAT2[cond4])*25)/(CONTAINDICE$VALSEUIL3[cond4]-CONTAINDICE$VALSEUIL2[cond4]))+25)
		CONTAINDICE$INDICECONTA[cond5]<-round((((CONTAINDICE$VALSEUIL4[cond5]-CONTAINDICE$RESULTAT2[cond5])*25)/(CONTAINDICE$VALSEUIL4[cond5]-CONTAINDICE$VALSEUIL3[cond5]))+0)
		CONTAINDICE$INDICECONTA[CONTAINDICE$RESULTAT2>CONTAINDICE$VALSEUIL4 & CONTAINDICE$CLASSECONTA==5]<-0
		CONTAINDICE$INDICECONTA[CONTAINDICE$INDICECONTA < 0]<-0
		CONTAINDICE$INDICECONTA[CONTAINDICE$INDICECONTA > 100]<-100
		rm(cond1, cond2, cond3, cond4,cond5,cond6)
	}

	
	if (NBSEUIL == 5) {

		CONTAINDICE$VALSEUIL5<-CONTAINDICE$VALSEUIL4 + (CONTAINDICE$VALSEUIL4 - CONTAINDICE$VALSEUIL3)

		CONTAINDICE$INDICECONTA[cond1]<-100
		CONTAINDICE$INDICECONTA[cond2]<-round((((CONTAINDICE$VALSEUIL1[cond2]-CONTAINDICE$RESULTAT2[cond2])*20)/(CONTAINDICE$VALSEUIL1[cond2]-0))+80)  
		CONTAINDICE$INDICECONTA[cond3]<-round((((CONTAINDICE$VALSEUIL2[cond3]-CONTAINDICE$RESULTAT2[cond3])*20)/(CONTAINDICE$VALSEUIL2[cond3]-CONTAINDICE$VALSEUIL1[cond3]))+60)
		CONTAINDICE$INDICECONTA[cond4]<-round((((CONTAINDICE$VALSEUIL3[cond4]-CONTAINDICE$RESULTAT2[cond4])*20)/(CONTAINDICE$VALSEUIL3[cond4]-CONTAINDICE$VALSEUIL2[cond4]))+40)
		CONTAINDICE$INDICECONTA[cond5]<-round((((CONTAINDICE$VALSEUIL4[cond5]-CONTAINDICE$RESULTAT2[cond5])*20)/(CONTAINDICE$VALSEUIL4[cond5]-CONTAINDICE$VALSEUIL3[cond5]))+20)
		CONTAINDICE$INDICECONTA[cond6]<-round((((CONTAINDICE$VALSEUIL5[cond6]-CONTAINDICE$RESULTAT2[cond6])*20)/(CONTAINDICE$VALSEUIL5[cond6]-CONTAINDICE$VALSEUIL4[cond6]))+0)
		CONTAINDICE$INDICECONTA[CONTAINDICE$RESULTAT2>CONTAINDICE$VALSEUIL4 & CONTAINDICE$CLASSECONTA==6]<-0
		CONTAINDICE$INDICECONTA[CONTAINDICE$INDICECONTA < 0]<-0
		CONTAINDICE$INDICECONTA[CONTAINDICE$INDICECONTA > 100]<-100
		rm(cond1, cond2, cond3, cond4,cond5)	
	

	}
	
	
# TABLEAU FINAL : mise en forme
	# Valeur (moyenne ou max)
	RLT_CONTAVALEUR<-data.frame(STATION = sort(unique(RLT_CONTA$STATION)))

	# Ajout colonnes des paramètres 
	PARAMETRECONTA_ETUDIE<-PARAMETRECONTA[PARAMETRECONTA$PARAMETRE %in% CONTAAGG$PARAMETRE,]

	for (i in  1:nrow(PARAMETRECONTA_ETUDIE)  ) {
		TEMPP<-CONTAINDICE[CONTAINDICE$PARAMETRE==PARAMETRECONTA_ETUDIE$PARAMETRE[i],c("STATION", "RESULTAT2")]
		names(TEMPP)[2]<-paste0 ("v.",PARAMETRECONTA_ETUDIE$NOMCOURT[i])
		RLT_CONTAVALEUR<-merge(RLT_CONTAVALEUR,TEMPP,by="STATION", all.x=TRUE)
		rm(TEMPP)
	}

# Indice
	RLT_CONTAINDICE<-data.frame(STATION = sort(unique(RLT_CONTA$STATION)))

	# Ajout colonnes des paramètres 
	PARAMETRECONTA_ETUDIE<-PARAMETRECONTA[PARAMETRECONTA$PARAMETRE %in% CONTAAGG$PARAMETRE,]

	for (i in  1:nrow(PARAMETRECONTA_ETUDIE)  ) {
		TEMPP<-CONTAINDICE[CONTAINDICE$PARAMETRE==PARAMETRECONTA_ETUDIE$PARAMETRE[i],c("STATION", "INDICECONTA")]
		names(TEMPP)[2]<-paste0("i.",PARAMETRECONTA_ETUDIE$NOMCOURT[i])
		RLT_CONTAINDICE<-merge(RLT_CONTAINDICE,TEMPP,by="STATION", all.x=TRUE)
		rm(TEMPP)
	}

## On assemble Indice et Valeur
RLT_CONTAINDICE<-merge(RLT_CONTAVALEUR,RLT_CONTAINDICE, by="STATION")

} 
