
###################################
# CALCUL ETAT CHIMIQUE - MASSE D'EAU
###################################
if (SEEECHIMME=="oui") {

	#ETAT AVEC HAPetUBI
		TEMPECHIMME<-merge(CHIMCMAMA[,c("STATION", "PARAGROUP","CLASSEETAT")], STATION[,c("STATION", "EUCD", "REPRESENTATIVE")], by="STATION")
		TEMPECHIMME_OUI<-TEMPECHIMME[TEMPECHIMME$REPRESENTATIVE %in% c("oui"),]
		TEMPECHIMME_TEMPO<-TEMPECHIMME[TEMPECHIMME$REPRESENTATIVE %in% c("temporaire"),]
		
		# Calcul de l'état ME pour les stations représentatives
		TEMPECHIMME_CAS1<-aggregate(CLASSEETAT ~ EUCD + REPRESENTATIVE, data = TEMPECHIMME_OUI, max)
		
		# Calcul de l'état ME pour les stations temporaires s'il n'y a pas de station représentative
		if (nrow(TEMPECHIMME_TEMPO)>0) {
			TEMPECHIMME_CAS2<-aggregate(CLASSEETAT ~ EUCD + REPRESENTATIVE, data = TEMPECHIMME_TEMPO, max)
			CHIMETATME<-rbind(TEMPECHIMME_CAS1,TEMPECHIMME_CAS2[!(TEMPECHIMME_CAS2$EUCD %in% c(TEMPECHIMME_CAS1$EUCD)),])
			rm(TEMPECHIMME_CAS2)
		} else {
			CHIMETATME<-TEMPECHIMME_CAS1
		}
	
		names(CHIMETATME)[3]<-"ETATCHIMME"
		
		
		
	#ETAT SANS HAPetUBI
	
	# CHIMETATME<-merge(CHIMETATME,CHIMHORSHAP, by="STATION", all.x = TRUE)
	
	
		# TEMPECHIMMESHAP<-merge(CHIMHORSHAP[,c("STATION","ETATCHIM_SSHAPUBI")], STATION[,c("STATION", "EUCD", "REPRESENTATIVE")], by="STATION")
		# TEMPECHIMMESHAP_OUI<-TEMPECHIMMESHAP[TEMPECHIMMESHAP$REPRESENTATIVE %in% c("oui"),]
		# TEMPECHIMMESHAP_TEMPO<-TEMPECHIMMESHAP[TEMPECHIMMESHAP$REPRESENTATIVE %in% c("temporaire"),]
		
		# # Calcul de l'état ME pour les stations représentatives
		# TEMPECHIMMESHAP_CAS1<-aggregate(ETATCHIM_SSHAPUBI ~ EUCD + REPRESENTATIVE, data = TEMPECHIMMESHAP_OUI, max)
		
		# # Calcul de l'état ME pour les stations temporaires s'il n'y a pas de station représentative
		# if (nrow(TEMPECHIMMESHAP_TEMPO)>0) {
			# TEMPECHIMMESHAP_CAS2<-aggregate(ETATCHIM_SSHAPUBI ~ EUCD + REPRESENTATIVE, data = TEMPECHIMMESHAP_TEMPO, max)
			# CHIMETATMESHAP<-rbind(TEMPECHIMMESHAP_CAS1,TEMPECHIMMESHAP_CAS2[!(TEMPECHIMMESHAP_CAS2$EUCD %in% c(TEMPECHIMMESHAP_CAS1$EUCD)),])
			# rm(TEMPECHIMMESHAP_CAS2)
		# } else {
			# CHIMETATMESHAP<-TEMPECHIMMESHAP_CAS1
		# }
	
		# names(CHIMETATMESHAP)[3]<-"ETATCHIMME_SSHAPUBI"	
	
	# #on rappatri les infos de ETATCHIMME_SSHAPUBI
	# CHIMETATME$ID<-paste(CHIMETATME$EUCD, CHIMETATME$REPRESENTATIVE)
	# CHIMETATMESHAP$ID<-paste(CHIMETATMESHAP$EUCD, CHIMETATMESHAP$REPRESENTATIVE)		
	# CHIMETATME<-merge(CHIMETATME,CHIMETATMESHAP[,c("ID","ETATCHIMME_SSHAPUBI")], by = "ID", all = TRUE)

	
###################################
# CALCUL ETAT CHIMIQUE - NIVEAU DE CONFIANCE
###################################
	CHIMETATME$NIVCONF<-as.numeric(NA)
	CHIMETATME$CAS<-as.character(NA)
	
	# Préparation des données pour l'estimation des % et data dispo (BENZO+INDENO & DEHP)
	NBPARAGLOBAL<-aggregate(PARAGROUP ~ FAMILLE, data = PARAGROUPCHIM , length)
	names(NBPARAGLOBAL)[2]<-"NBTOTAL"
	NBPARAGLOBAL$GLOBAL<-"station"
	NBPARAGLOBALSTAT<-aggregate(NBTOTAL ~ GLOBAL , data = NBPARAGLOBAL , sum)
	
	TEMPOCHIMSTATGLOB<-aggregate(PARAGROUP ~ STATION + CLASSEETAT, data = CHIMCMAMA , length)
	names(TEMPOCHIMSTATGLOB)[3]<-"NBPARA"
	# calcul ratio % global
	TEMPOCHIMSTATGLOB<-cbind(TEMPOCHIMSTATGLOB,NBPARAGLOBALSTAT)
	TEMPOCHIMSTATGLOB$RATIO<-round((TEMPOCHIMSTATGLOB$NBPARA/TEMPOCHIMSTATGLOB$NBTOTAL)*100,0)
	TEMPOCHIMSTATGLOB$ID<-paste(TEMPOCHIMSTATGLOB$STATION,TEMPOCHIMSTATGLOB$CLASSEETAT,sep="_")
	
	#selection DATA pour calcul du niveau de confiance
	TEMPORATIOBON<-TEMPOCHIMSTATGLOB[c(TEMPOCHIMSTATGLOB$CLASSEETAT==1),c("STATION", "RATIO","CLASSEETAT")]
	
	TEMPODISPBENZO<-CHIMCMAMA[c(CHIMCMAMA$PARAGROUP %in% c("28_1","28_2","28_3","28_4","28_5") & CHIMCMAMA$CLASSEETAT==1) ,c("STATION","CLASSEETAT")]
	if (nrow(TEMPODISPBENZO) > 0){
	TEMPODISPBENZO$BENZO<-as.character("BE")} else {TEMPODISPBENZO$BENZO<-as.character()}
	
	TEMPODISPDEHP<-CHIMCMAMA[c(CHIMCMAMA$PARAGROUP=="12" & CHIMCMAMA$CLASSEETAT==1),c("STATION","CLASSEETAT")]
	if (nrow(TEMPODISPDEHP) > 0){
	TEMPODISPDEHP$DEHP<-as.character("BE")} else {TEMPODISPDEHP$DEHP<-as.character() }
	
	TEMPODISPPARA<-merge(TEMPODISPBENZO,TEMPODISPDEHP,by="STATION", all.x=TRUE, all.y=TRUE)
	
	TEMPORATIOBON<-merge(TEMPORATIOBON,TEMPODISPPARA[,c("STATION","BENZO","DEHP")], by="STATION", all.x=TRUE)
	
	# Ajout du code station au résultat masse d'eau necessaire pour info sur le niveau de confiance	
	CHIMETATME$ID<-paste(CHIMETATME$EUCD,CHIMETATME$ETATCHIMME,CHIMETATME$REPRESENTATIVE,sep="_")
	TEMPSTATION<-RLT_CHIMSTATION[,c("STATION","ETATCHIM","ETATCHIM_SSHAPUBI")]
	TEMPSTATION<-merge(TEMPSTATION,STATION[,c("STATION", "EUCD", "REPRESENTATIVE")],by="STATION")
	TEMPSTATION$ID<-paste(TEMPSTATION$EUCD,TEMPSTATION$ETATCHIM,TEMPSTATION$REPRESENTATIVE,sep="_")
	CHIMETATME<-merge(CHIMETATME,TEMPSTATION[,c("ID", "STATION","REPRESENTATIVE")],by="ID")
		
	# Calcul niveau de confiance
	CHIMETATME$NIVCONF[CHIMETATME$ETATCHIMME==2]<-3
	CHIMETATME$CAS[CHIMETATME$ETATCHIMME==2]<-"Q1"
	CHIMETATME$NIVCONF[CHIMETATME$ETATCHIMME==1 & CHIMETATME$STATION %in% TEMPORATIOBON$STATION[TEMPORATIOBON$RATIO>=80 & !is.na(TEMPORATIOBON$BENZO) & !is.na(TEMPORATIOBON$DEHP)]]<-3
	CHIMETATME$CAS[CHIMETATME$ETATCHIMME==1 & CHIMETATME$STATION %in% TEMPORATIOBON$STATION[TEMPORATIOBON$RATIO>=80 & !is.na(TEMPORATIOBON$BENZO) & !is.na(TEMPORATIOBON$DEHP)]]<-"Q2"
	CHIMETATME$NIVCONF[CHIMETATME$ETATCHIMME==1 & CHIMETATME$STATION %in% TEMPORATIOBON$STATION[TEMPORATIOBON$RATIO>=50 & TEMPORATIOBON$RATIO <80 & !is.na(TEMPORATIOBON$BENZO) & !is.na(TEMPORATIOBON$DEHP)]]<-2
	CHIMETATME$CAS[CHIMETATME$ETATCHIMME==1 & CHIMETATME$STATION %in% TEMPORATIOBON$STATION[TEMPORATIOBON$RATIO>=50 & TEMPORATIOBON$RATIO <80 & !is.na(TEMPORATIOBON$BENZO) & !is.na(TEMPORATIOBON$DEHP)]]<-"Q3"
	CHIMETATME$NIVCONF[CHIMETATME$ETATCHIMME==1 & CHIMETATME$STATION %in% TEMPORATIOBON$STATION[TEMPORATIOBON$RATIO <50]]<-1
	CHIMETATME$CAS[CHIMETATME$ETATCHIMME==1 & CHIMETATME$STATION %in% TEMPORATIOBON$STATION[TEMPORATIOBON$RATIO <50]]<-"Q4"
	CHIMETATME$NIVCONF[CHIMETATME$ETATCHIMME==1 & is.na(CHIMETATME$NIVCONF) ]<-1
	CHIMETATME$CAS[CHIMETATME$ETATCHIMME==1 & is.na(CHIMETATME$CAS)]<-"Q5"
	CHIMETATME$NIVCONF[CHIMETATME$ETATCHIMME==0]<-0
	CHIMETATME$CAS[CHIMETATME$ETATCHIMME==0]<-"Q6"
	rm(TEMPOCHIMSTATGLOB,TEMPODISPBENZO,TEMPODISPDEHP,TEMPODISPPARA,TEMPORATIOBON)
	gc()

################################
# TABLE FINALE - mise en forme
###############################
	
	RLT_CHIMETATME<-CHIMETATME[,c("EUCD","ETATCHIMME","NIVCONF","CAS","STATION")]
	RLT_CHIMETATME<-merge(RLT_CHIMETATME,RLT_CHIMSTATION,by="STATION")
	NAMES_RLTSTATION<-names(RLT_CHIMSTATION[,c(2:ncol(RLT_CHIMSTATION))])
	RLT_CHIMETATME<-RLT_CHIMETATME[,c("EUCD","ETATCHIMME","NIVCONF","CAS","STATION",NAMES_RLTSTATION)]
	RLT_CHIMETATME<-RLT_CHIMETATME[order(RLT_CHIMETATME$EUCD),]
	RLT_CHIMETATME<-merge(RLT_CHIMETATME,MASSEDEAU[,c("EUCD","NAME","MODIFIED","ARTIFICIAL","ECHELLEME")],by = "EUCD",all.x = TRUE)
	
	

	#PPL, 24/09/20145
	# Pour supprimer les doublons de ME les règles seraient les suivantes :  
	# •	Sélection de la ligne avec l’état chimique le plus déclassant 
	# •	Si même état : sélection de la ligne avec le meilleur niveau de confiance
	# •	Si même niveau de confiance : sélection de la ligne avec le plus de paramètres déclassant
	# •	Si même nombre de paramètres déclassant : sélection de la ligne avec moins d’état paramètre inconnu 
	# •	Si idem : sélection au hasard.
	
	print(nrow(RLT_CHIMETATME))
	RLT_CHIMETATME<-RLT_CHIMETATME[order(RLT_CHIMETATME$EUCD, -RLT_CHIMETATME$ETATCHIMME, RLT_CHIMETATME$NIVCONF,  -RLT_CHIMETATME$N_CHIMDECLASS, RLT_CHIMETATME$N_PARAM_IND ),]
	RLT_CHIMETATME<-RLT_CHIMETATME[!duplicated(RLT_CHIMETATME[ ,c("EUCD")]),]
	print(nrow(RLT_CHIMETATME))
	
	
	rm(TEMPECHIMME_OUI,TEMPECHIMME_TEMPO,TEMPECHIMME_CAS1,TEMPSTATION)
	gc()

	flush.console()
	
	
	#### METTRE TOUT EN MAJUSCULE
	names(RLT_CHIMETATME)<-toupper(names(RLT_CHIMETATME))
	
	
	#############################################
	## RAJOUTER STATIONTXT 
	RLT_CHIMETATME_NAMES<-names(RLT_CHIMETATME)
	if (nchar(as.character(RLT_CHIMETATME$STATION))[1] == 7 & !is.na(RLT_CHIMETATME$STATION[1])) {
			RLT_CHIMETATME$STATIONTXT<-as.character(RLT_CHIMETATME$STATION)
			RLT_CHIMETATME$STATIONTXT[nchar(as.character(RLT_CHIMETATME$STATION)) == 7 & !is.na(RLT_CHIMETATME$STATION)]<-paste("0",RLT_CHIMETATME$STATION[nchar(as.character(RLT_CHIMETATME$STATION)) == 7 & !is.na(RLT_CHIMETATME$STATION)],sep="")
			RLT_CHIMETATME<-RLT_CHIMETATME[,c(RLT_CHIMETATME_NAMES,"STATIONTXT")]
			RLT_CHIMETATME_NAMES<-names(RLT_CHIMETATME)
	}

	
	
}

